name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: hugo deploy
